apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service
  namespace: {{ .Values.namespace }}
  {{- if .Values.serviceAccount.irsaRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.irsaRoleArn }}
  {{- end }}
