apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: {{ .Values.namespace }}
  labels:
    app: product-service
    project: cloudmart
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: product-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: product-service
    spec:
      serviceAccountName: product-service
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: product-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8001
          env:
            - name: DYNAMODB_TABLE
              valueFrom:
                configMapKeyRef:
                  name: product-service-config
                  key: dynamodbTableName
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: product-service-config
                  key: awsRegion
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
