server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /health { return 200 "ok"; add_header Content-Type text/plain; }
    location /api/products { proxy_pass http://product-service:8001; }
    location /api/orders   { proxy_pass http://order-service:8002; }
    location /api/users    { proxy_pass http://user-service:8003; }
    location / { try_files $uri $uri/ /index.html; }
}
